version: '3.4'

services:
  companyprojectpricelistservice:
   image: ${DOCKER_REGISTRY-}companyprojectpricelistservice
   build:
      context: .
      dockerfile: CompanyProjectPriceListService/CompanyProjectPriceListService/Dockerfile

  companyprojectcardsservice:
    image: ${DOCKER_REGISTRY-}companyprojectcardsservice
    build:
      context: .
      dockerfile: CompanyProjectCardsService/Dockerfile


  companyprojectcontentservice:
    image: ${DOCKER_REGISTRY-}companyprojectcontentservice
    build:
      context: .
      dockerfile: CompanyProjectContent/Dockerfile


  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: OcelotApiGateway/Dockerfile

  companyprojectmessage:
    image: ${DOCKER_REGISTRY-}companyprojectmessageservice
    build:
      context: .
      dockerfile: CompanyProjectMessageService/Dockerfile


  companyprojectaddressservice:
    image: ${DOCKER_REGISTRY-}companyprojectaddressservice
    build:
      context: .
      dockerfile: CompanyProjectAddressService/Dockerfile

