version: '3.4'

services:
  companyprojectpricelistservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2000:80"

  companyprojectcardsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2001:80"


  companyprojectcontentservice:
    container_name: companyprojectcontentservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5012:80"


  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #depends_on:
    #  - companyprojectcontentservice
    ports:
      - "8010:80"

