version: '3.4'

services:
  companyprojectpricelistservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5012:80"

  companyprojectcardsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5011:80"

  companyprojectcontentservice:
    container_name: companyprojectcontentservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"

  companyprojectmessageservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5013:80"

  companyprojectaddressservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5014:80"
    
  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"

