version: '3.4'

services:
  companyprojectpricelistservice:
    image: ${DOCKER_REGISTRY-}companyprojectpricelistservice
    expose:
      - "80"
    ports:
      #- 4000:5012
      - "5012:80"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    build:
      context: .
      dockerfile: CompanyProjectPriceListService/CompanyProjectPriceListService/Dockerfile

  companyprojectcardsservice:
    image: ${DOCKER_REGISTRY-}companyprojectcardsservice
    build:
      context: .
      dockerfile: CompanyProjectCardsService/Dockerfile


  companyprojectcontentservice:
    image: ${DOCKER_REGISTRY-}companyprojectcontentservice
    build:
      context: .
      dockerfile: CompanyProjectContent/Dockerfile


  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: OcelotApiGateway/Dockerfile

