// <auto-generated />
using System;
using CompanyProjectOrderService.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyProjectOrderService.Migrations
{
    [DbContext(typeof(CompanyProjectOrderDbContext))]
    [Migration("20230530002312_InitialOrders")]
    partial class InitialOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyProjectOrderService.Model.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApartmentOrOfficeNumber")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PopulatedArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CompanyProjectOrderService.Model.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<Guid?>("AddressDataAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialInstruction")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeOfFailure")
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressDataAddressId");

                    b.ToTable("Orders");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("CompanyProjectOrderService.Model.Order", b =>
                {
                    b.HasOne("CompanyProjectOrderService.Model.Address", "AddressData")
                        .WithMany()
                        .HasForeignKey("AddressDataAddressId");

                    b.Navigation("AddressData");
                });
#pragma warning restore 612, 618
        }
    }
}
