// <auto-generated />
using System;
using CompanyProject.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CompanyProject.API.Migrations
{
    [DbContext(typeof(CompanyProjectDbContext))]
    partial class CompanyProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CompanyProject.Domain.CompanyContactAggregate.CompanyContact", b =>
                {
                    b.Property<int>("CompanyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<bool>("ToUse")
                        .HasColumnType("boolean");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text");

                    b.Property<string>("WorkTime")
                        .HasColumnType("text");

                    b.HasKey("CompanyContactId");

                    b.ToTable("CompanyContacts");

                    b.HasData(
                        new
                        {
                            CompanyContactId = 1,
                            Address = "РФ, Ставропольский край, Минераловодский городской округ, п. Бородыновка, ул. Железнодорожная 7а, 2",
                            CompanyName = "<span class=\"has-text-black\">Нова<span> <span class=\"color-title\">Компьютерс</span>",
                            PhoneNumber = "+7-(900)-000-00-00",
                            ToUse = true,
                            WhatsApp = "+7-(900)-000-00-00",
                            WorkTime = "9:00 - 19:00, выходной: понедельник"
                        });
                });

            modelBuilder.Entity("CompanyProject.Domain.CustomerAggregate.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AnotherPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ApartmentOrOffice")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdoptedPrivacyPolicy")
                        .HasColumnType("boolean");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("CustomerId");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CompanyProject.Domain.EmployeeAggregate.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CompanyProject.Domain.EmployeeAggregate.EmployeeCustomer", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("EmployeeCustomer");
                });

            modelBuilder.Entity("CompanyProject.Domain.FeedbackAggregate.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FeedbackText")
                        .HasColumnType("character varying(280)")
                        .HasMaxLength(280);

                    b.Property<int>("OrderForeignKey")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint")
                        .HasMaxLength(1);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("FeedbackId");

                    b.HasIndex("OrderForeignKey")
                        .IsUnique();

                    b.HasIndex("FeedbackId", "FeedbackText", "Rating");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("CompanyProject.Domain.MessageAggregate.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdoptedPrivacyPolicy")
                        .HasColumnType("boolean");

                    b.Property<string>("PeopleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectMessage")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CompanyProject.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreateTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("30.10.2020 0:00");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RealPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("SpecialInstruction")
                        .HasColumnType("text");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("TypeOfFailure")
                        .HasColumnType("text");

                    b.Property<string>("VisitTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VisitTime");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CompanyProject.Domain.PageAggregate.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScreenName")
                        .HasColumnType("text");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<bool>("ToCard")
                        .HasColumnType("boolean");

                    b.Property<bool>("ToNavbar")
                        .HasColumnType("boolean");

                    b.HasKey("PageId");

                    b.HasIndex("Name");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            PageId = 1,
                            Name = "Index",
                            ToCard = false,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 2,
                            Icon = "fas fa-wrench",
                            Name = "ComputersRepair",
                            ScreenName = "Ремонт компьютеров",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 3,
                            Icon = "fas fa-laptop-medical",
                            Name = "LaptopsRepair",
                            ScreenName = "Ремонт ноутбуков",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 4,
                            Icon = "fas fa-ambulance",
                            Name = "HelpDesk",
                            ScreenName = "Компьютерная помощь",
                            ToCard = true,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 5,
                            Icon = "fas fa-network-wired",
                            Name = "InternetNetworks",
                            ScreenName = "Интернет и сети",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 6,
                            Icon = "fas fa-database",
                            Name = "DataRecovery",
                            ScreenName = "Восстановление данных",
                            ToCard = true,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 7,
                            Icon = "fas fa-industry",
                            Name = "B2b",
                            ScreenName = "ИТ-услуги для бизнеса",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 8,
                            Icon = "fas fa-laptop",
                            Name = "LaptopUpgrade",
                            ScreenName = "Модернизация ноутбука",
                            ToCard = true,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 9,
                            Icon = "fas fa-tv",
                            Name = "PcAssembly",
                            ScreenName = "Сборка компьютера",
                            ToCard = true,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 10,
                            Icon = "fas fa-print",
                            Name = "OfficeEquipment",
                            ScreenName = "Oргтехника",
                            ToCard = false,
                            ToNavbar = true
                        });
                });

            modelBuilder.Entity("CompanyProject.Domain.ParagraphAggregate.Paragraph", b =>
                {
                    b.Property<int>("ParagraphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string[]>("Content")
                        .HasColumnType("text[]");

                    b.Property<bool>("HasPicture")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlobalTitle")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsList")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMobileVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubtitle")
                        .HasColumnType("boolean");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("PicturePath")
                        .HasColumnType("text");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ParagraphId");

                    b.HasIndex("Content");

                    b.HasIndex("PageId");

                    b.ToTable("Paragraphs");

                    b.HasData(
                        new
                        {
                            ParagraphId = 1,
                            Content = new[] { "Компьютерный мастер на Кавказских Минеральных Водах" },
                            HasPicture = false,
                            IsGlobalTitle = true,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 2,
                            Content = new[] { "Компания «Nova Computers» предлагает Вам качественные и недорогие компьютерные услуги по обслуживанию, ремонту компьютеров, ноутбуков и офисной техники в регионе Кавказских Минеральных Вод (Минеральные Воды, Пятигорск, Ессентуки, Кисловодск). Ремонт может проводиться мастером как территории заказчика, так и в нашем сервисном центре. Мы всегда рады оперативно оказать Вам профессиональную компьютерную помощь, обращайтесь!" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 3,
                            Content = new[] { "NeedHelpAndPicturePV" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = false,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 4,
                            Content = new[] { "Вызов компьютерного мастера на дом" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 5,
                            Content = new[] { "Высококвалифицированные специалисты компании «Nova Computers» имеют большой опыт в ремонте и обслуживании любых моделей компьютеров, ноутбуков, роутеров и других видов цифровой и вычислительной техники.", "Для определения неполадок компьютера или ноутбука нашему специалисту необходимо провести начальную диагностику Вашего оборудования, с целью составления сметы на ремонт.", "Наши мастера делают только те работы, которые необходимы; мы никогда не занимамся навязыванием дополнительных, зачастую ненужных, услуг." },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 6,
                            Content = new[] { "Как вызвать компьютерного мастера на дом или в офис?" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 7,
                            Content = new[] { "Позвоните нам или оставьте заявку на сайте в соответствующей форме;", "Опишите Вашу проблему;", "Согласуйте время приезда компьютерного мастера." },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = true,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 8,
                            Content = new[] { "Оказываем услуги по ремонту в городах Кавказских Минеральных Вод (Минеральные Воды, Пятигорск, Ессентуки, Кисловодск) и в прилегающих носеленных пунктах." },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 9,
                            Content = new[] { "Как скоро приедет мастер? Сколько будут стоить услуги по ремонту?" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 10,
                            Content = new[] { "Мастер приедет в заранее согласованное с Вами время;", "Перед началом работ по настройке или ремонту компьютера, ноутбука или офисной техники специалисту необходимо будет провести диагностику;", "Подробные цены на ремонт и компьютерные услуги компании «Нова Компьютерс» Вы можете узнать в соответствующем разделе" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = true,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 11,
                            Content = new[] { "Ремонт компьютеров на дому или в офисе" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 12,
                            Content = new[] { "Мы готовы помочь Вам с ремонтом компьютера. Специалисты нашей компании выполняют профессиональный ремонт компьютеров любых производителей недорого и в минимально возможные сроки." },
                            HasPicture = true,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1,
                            PicturePath = "~/Resources/Images/remont-komputerov.jpg"
                        },
                        new
                        {
                            ParagraphId = 13,
                            Content = new[] { "Каков порядок ремонта компьютеров? Где будут выполняться работы?" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 14,
                            Content = new[] { "Ремонт стационарных компьютеров может выполняться как у Вас на дому или в офисе, так и у нас в сервисном центре;", "Может потребоваться специальное оборудование или дополнительные запчасти. В этом случае наш специалист при Вашем желании может доставить компьютер в сервисный центр, провести работы по ремонту, а затем привезти обратно к Вам." },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = true,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 15,
                            Content = new[] { "Компьютерная помощь срочно и без проблем!" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 16,
                            Content = new[] { "Компания «Nova Computers» всегда рада оказать Вам срочную компьютерную помощь! Мы выполним любые Ваши пожелания по ремонту и настройке компьютера, ноутбука, роутера, МФУ, принтера. Так же поможем установить Windows или иную операционную систему, скачать и установить любые программы и утилиты." },
                            HasPicture = true,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1,
                            PicturePath = "~/Resources/Images/komputernaya-pomosh.png"
                        },
                        new
                        {
                            ParagraphId = 17,
                            Content = new[] { "Какие услуги компьютерной помощи мы можем оказать?" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 18,
                            Content = new[] { "В число компьютерных услуг входит так же помощь по установке антивирусов, драйверов, обучение пользователей работе на компьютере и прочее;", "Учтем все Ваши пожелания, обращайтесь! Мы поможем!" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = true,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        });
                });

            modelBuilder.Entity("CompanyProject.Domain.PriceListAggregate.PriceList", b =>
                {
                    b.Property<int>("PriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("IdServiceName")
                        .HasColumnType("text");

                    b.Property<string[]>("NeedWorks")
                        .HasColumnType("text[]");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Service")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<string>("ServicePrice")
                        .HasColumnType("text");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("PriceListId");

                    b.HasIndex("PageId");

                    b.ToTable("PriceLists");

                    b.HasData(
                        new
                        {
                            PriceListId = 1,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена материнской платы компьютера", "Замена блока питания компьютера", "Работы по замене шлейфов или питающих кабелей", "Ремонт блока питания (проводится в сервисном центре)", "Восстановление работоспособности (замена) кнопки включения", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Не включается компьютер",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 2,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена материнской платы компьютера", "Замена блока питания компьютера", "Работы по замене шлейфов или питающих кабелей", "Ремонт блока питания (проводится в сервисном центре)", "Восстановление работоспособности (замена) кнопки включения", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Красный экран на компьютере",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 3,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка Windows XP - Windows 10", "Поиск и установка драйверов устройств", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы", "Удаление временных, мусорных системных файлов", "Чистка системного реестра Windows", "Устранение последствий действия вирусов, восстановление работы операционной системы", "Выявление и устранение неполадок программного обеспечения", "Поиск и исправление ошибок системного реестра Windows", "Настройка таймингов оперативной памяти в BIOS", "Устранение перегрева компьютера, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Основная антивирусная профилактика (удаление СМС-вымогателя, трояна, баннера, других вирусов)", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Синий экран на компьютере",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 4,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы", "Настройка автозагрузки Windows", "Удаление временных, мусорных системных файлов", "Чистка системного реестра Windows", "Выявление и устранение неполадок программного обеспечения", "Поиск и исправление ошибок системного реестра Windows", "Настройка таймингов оперативной памяти в BIOS", "Основная антивирусная профилактика (удаление СМС-вымогателя, трояна, баннера, других вирусов)", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Ошибки в работе компьютера",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "2500"
                        },
                        new
                        {
                            PriceListId = 5,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка Windows XP - Windows 10", "Настройка автозагрузки Windows", "Удаление временных, мусорных системных файлов", "Чистка системного реестра Windows", "Поиск и исправление ошибок системного реестра Windows", "Устранение перегрева компьютера, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Основная антивирусная профилактика (удаление СМС-вымогателя, трояна, баннера, других вирусов)", "Глубокая антивирусная профилактика (устранение последствий действия вирусов, восстановление работы операционной системы)", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Зависает компьютер",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 6,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Выявление и устранение неполадок программного обеспечения", "Замена оперативной памяти компьютера", "Устранение перегрева компьютера, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Самопроизвольная перезагрузка компьютера",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 7,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена вентилятора (кулера) компьютера", "Замена системы охлаждения компьютера", "Устранение перегрева компьютера, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Шумит компьютер",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 8,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена вентилятора (кулера) компьютера", "Замена системы охлаждения компьютера", "Устранение перегрева компьютера, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Перегревается компьютер",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 9,
                            IdServiceName = "computers-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка Windows XP - Windows 10", "Основная антивирусная профилактика (удаление СМС-вымогателя, трояна, баннера, других вирусов)", "Замена материнской платы компьютера", "Замена блока питания компьютера", "Замена жесткого диска компьютера", "Замена вентилятора (кулера) компьютера", "Замена системы охлаждения компьютера", "Работы по замене шлейфов или питающих кабелей", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Прочие проблемы с компьютером",
                            ServiceName = "Ремонт компьютеров",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 10,
                            IdServiceName = "computer-assistance-pc",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка Windows XP - Windows 10", "Поиск и установка драйвера устройства", "Индивидуальные настройки операционной системы", "Разбивка жесткого диска на разделы", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Установка Windows (включая установку драйверов на оборудование)",
                            ServiceName = "Компьютерная помощь (компьютер)",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 11,
                            IdServiceName = "computer-assistance-pc",
                            NeedWorks = new[] { "Диагностика оборудования", "Основная антивирусная профилактика (удаление СМС-вымогателя, трояна, баннера, других вирусов)", "Глубокая антивирусная профилактика (Устранение последствий действия вирусов, восстановление работы операционной системы)", "Установка Windows XP - Windows 10", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Удаление вирусов",
                            ServiceName = "Компьютерная помощь (компьютер)",
                            ServicePrice = "1000"
                        },
                        new
                        {
                            PriceListId = 12,
                            IdServiceName = "computer-assistance-pc",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка программ" },
                            PageId = 2,
                            Service = "Установка программ (один экземпляр)",
                            ServiceName = "Компьютерная помощь (компьютер)",
                            ServicePrice = "200"
                        },
                        new
                        {
                            PriceListId = 13,
                            IdServiceName = "computer-assistance-pc",
                            NeedWorks = new[] { "Диагностика оборудования", "Подбор и установка любого антивируса", "Подбор и установка фаервола", "Индивидуальная тонкая настройка антивируса, фаервола или брандмауэра", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Установка и настройка антивируса",
                            ServiceName = "Компьютерная помощь (компьютер)",
                            ServicePrice = "700"
                        },
                        new
                        {
                            PriceListId = 14,
                            IdServiceName = "computer-assistance-pc",
                            NeedWorks = new[] { "Диагностика оборудования", "Поиск и установка драйвера устройства", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы" },
                            PageId = 2,
                            Service = "Установка драйверов (один экземпляр)",
                            ServiceName = "Компьютерная помощь (компьютер)",
                            ServicePrice = "300"
                        },
                        new
                        {
                            PriceListId = 15,
                            IdServiceName = "computer-assistance-pc",
                            NeedWorks = new[] { "Диагностика оборудования", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы", "Настройка автозагрузки Windows", "Индивидуальные настройки операционной системы", "Удаление временных, мусорных системных файлов", "Чистка системного реестра Windows", "Индивидуальная тонкая настройка антивируса, фаервола или брандмауэра", "Выявление и устранение неполадок программного обеспечения", "Прочие необходимые работы" },
                            PageId = 2,
                            Service = "Настройка компьютера",
                            ServiceName = "Компьютерная помощь (компьютер)",
                            ServicePrice = "1000"
                        },
                        new
                        {
                            PriceListId = 16,
                            IdServiceName = "pc-assembly",
                            NeedWorks = new[] { "Сборка компьютера на заказ" },
                            PageId = 2,
                            Service = "Сборка компьютера на заказ",
                            ServiceName = "Сборка компьютера",
                            ServicePrice = "10% от стоимости компьютера + 500"
                        },
                        new
                        {
                            PriceListId = 17,
                            IdServiceName = "pc-assembly",
                            NeedWorks = new[] { "Диагностика оборудования", "Модернизация компьютера на заказ" },
                            PageId = 2,
                            Service = "Модернизация компьютера на заказ",
                            ServiceName = "Сборка компьютера",
                            ServicePrice = "10% от стоимости новых комплектующих + 500"
                        },
                        new
                        {
                            PriceListId = 18,
                            IdServiceName = "pc-service",
                            NeedWorks = new[] { "Частичная разборка системного блока", "Чистка системы охлаждения процессора от пыли", "Чистка системы охлаждения видеокарты от пыли", "Чистка системы охлаждения материнмкой платы от пыли", "Замена пермопасты на процессоре", "Замена пермопасты на чипе видеокарты" },
                            PageId = 2,
                            Service = "Чистка компьютера от пыли с заменой термопасты",
                            ServiceName = "Обслуживание компьютера",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 19,
                            IdServiceName = "pc-service",
                            NeedWorks = new[] { "Чистка системы охлаждения процессора от пыли", "Чистка системы охлаждения видеокарты от пыли", "Чистка системы охлаждения материнмкой платы от пыли" },
                            PageId = 2,
                            Service = "Чистка компьютера от пыли без разборки системного блока",
                            ServiceName = "Обслуживание компьютера",
                            ServicePrice = "1000"
                        },
                        new
                        {
                            PriceListId = 20,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена материнской платы ноутбука", "Замена жесткого диска ноутбука", "Замена оперативной памяти ноутбука", "Замена видеокарты ноутбука", "Работы по замене шлейфа или питающих кабелей ноутбука", "Ремонт цепи питания ноутбука", "Ремонт материнской платы ноутбука", "Устранение перегрева ноутбука, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Не включается ноутбук",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "2500"
                        },
                        new
                        {
                            PriceListId = 21,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена оперативной памяти ноутбука", "Замена видеокарты ноутбука", "Замена жесткого диска ноутбука", "Замена материнской платы ноутбука", "Ремонт системы охлаждения ноутбука", "Восстановление работоспособности жесткого диска ноутбука, повторная разметка секторов (Remap)", "Устранение перегрева ноутбука, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Синий экран на ноутбуке",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "2500"
                        },
                        new
                        {
                            PriceListId = 22,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена материнской платы ноутбука", "Замена блока питания ноутбука", "Работы по замене шлейфов или питающих кабелей", "Ремонт блока питания (проводится в сервисном центре)", "Замена отдельных комплектующих ноутбука", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Красный экран на ноутбуке",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "2500"
                        },
                        new
                        {
                            PriceListId = 23,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы", "Настройка автозагрузки Windows", "Удаление временных, мусорных системных файлов", "Чистка системного реестра Windows", "Основная антивирусная профилактика (удаление СМС-вымогателя, трояна, баннера, других вирусов) ", "Выявление и устранение неполадок программного обеспечения", "Поиск и исправление ошибок системного реестра Windows", "Восстановление работоспособности жесткого диска ноутбука, повторная разметка секторов (Remap)", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Ошибки в работе ноутбука",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "3000"
                        },
                        new
                        {
                            PriceListId = 24,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка Windows XP - Windows 10", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы", "Удаление временных, мусорных системных файлов", "Чистка системного реестра Windows", "Глубокая антивирусная профилактика (устранение последствий действия вирусов, восстановление работы операционной системы)", "Выявление и устранение неполадок программного обеспечения", "Поиск и исправление ошибок системного реестра Windows", "Ремонт системы охлаждения ноутбука", "Устранение перегрева ноутбука, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Зависает ноутбук",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "2500"
                        },
                        new
                        {
                            PriceListId = 25,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы", "Чистка системного реестра Windows", "Выявление и устранение неполадок программного обеспечения", "Поиск и исправление ошибок системного реестра Windows", "Ремонт системы охлаждения ноутбука", "Устранение перегрева ноутбука, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Замена оперативной памяти ноутбука", "Ремонт цепи питания ноутбука", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Самопроизвольная перезагрузка ноутбука",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "2500"
                        },
                        new
                        {
                            PriceListId = 26,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена вентилятора (кулера) ноутбука", "Ремонт системы охлаждения ноутбука", "Устранение перегрева ноутбука, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Шумит ноутбук",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 27,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Замена вентилятора (кулера) ноутбука", "Ремонт системы охлаждения ноутбука", "Устранение перегрева ноутбука, профилактические работы, чистка от пыли, замена термопасты и термопрокладок", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Перегревается ноутбук",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 28,
                            IdServiceName = "laptop-repair",
                            NeedWorks = new[] { "Диагностика оборудования", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Прочие проблемы с ноутбуком",
                            ServiceName = "Ремонт ноутбуков",
                            ServicePrice = "2500"
                        },
                        new
                        {
                            PriceListId = 29,
                            IdServiceName = "computer-assistance-laptop",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка Windows XP - Windows 10", "Поиск и установка драйвера устройства", "Индивидуальные настройки операционной системы", "Разбивка жесткого диска на разделы", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Установка Windows (включая установку драйверов на оборудование)",
                            ServiceName = "Компьютерная помощь (ноутбук)",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 30,
                            IdServiceName = "computer-assistance-laptop",
                            NeedWorks = new[] { "Диагностика оборудования", "Основная антивирусная профилактика (удаление СМС-вымогателя, трояна, баннера, других вирусов)", "Глубокая антивирусная профилактика (Устранение последствий действия вирусов, восстановление работы операционной системы)", "Установка Windows XP - Windows 10", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Удаление вирусов",
                            ServiceName = "Компьютерная помощь (ноутбук)",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 31,
                            IdServiceName = "computer-assistance-laptop",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка программ" },
                            PageId = 3,
                            Service = "Установка программ (один экземпляр)",
                            ServiceName = "Компьютерная помощь (ноутбук)",
                            ServicePrice = "400"
                        },
                        new
                        {
                            PriceListId = 32,
                            IdServiceName = "computer-assistance-laptop",
                            NeedWorks = new[] { "Диагностика оборудования", "Подбор и установка любого антивируса", "Подбор и установка фаервола", "Индивидуальная тонкая настройка антивируса, фаервола или брандмауэра", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Установка и настройка антивируса",
                            ServiceName = "Компьютерная помощь (ноутбук)",
                            ServicePrice = "1000"
                        },
                        new
                        {
                            PriceListId = 33,
                            IdServiceName = "computer-assistance-laptop",
                            NeedWorks = new[] { "Диагностика оборудования", "Поиск и установка драйвера устройства", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы" },
                            PageId = 3,
                            Service = "Установка драйверов (один экземпляр)",
                            ServiceName = "Компьютерная помощь (ноутбук)",
                            ServicePrice = "600"
                        },
                        new
                        {
                            PriceListId = 34,
                            IdServiceName = "computer-assistance-laptop",
                            NeedWorks = new[] { "Диагностика оборудования", "Восстановление корректной работы, обеспечение совместимости драйвера с текущей версией операционной системы", "Настройка автозагрузки Windows", "Индивидуальные настройки операционной системы", "Удаление временных, мусорных системных файлов", "Чистка системного реестра Windows", "Индивидуальная тонкая настройка антивируса, межсетевго экрана (фаервола или брандмауэра)", "Выявление и устранение неполадок программного обеспечения", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Настройка ноутбука",
                            ServiceName = "Компьютерная помощь (ноутбук)",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 35,
                            IdServiceName = "laptop-upgrade",
                            NeedWorks = new[] { "Диагностика аппаратной части ноутбука", "Подбор и замена модулей оперативной памяти ноутбука", "Подбор и установка нового жесткого диска или SSD" },
                            PageId = 3,
                            Service = "Расширение памяти ноутбука",
                            ServiceName = "Модернизация ноутбука",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 36,
                            IdServiceName = "laptop-upgrade",
                            NeedWorks = new[] { "Диагностика аппаратной части ноутбука", "Подбор и замена модулей оперативной памяти ноутбука", "Подбор и установка скоростного жесткого диска или SSD", "Подбор и установка новой видеокарты или процессора", "Прочие необходимые работы" },
                            PageId = 3,
                            Service = "Увеличение скорости работы ноутбука",
                            ServiceName = "Модернизация ноутбука",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 37,
                            IdServiceName = "laptop-service",
                            NeedWorks = new[] { "Частичная разборка ноутбука", "Чистка системы охлаждения процессора от пыли", "Чистка системы охлаждения видеокарты от пыли", "Чистка системы охлаждения материнмкой платы от пыли", "Замена пермопасты на процессоре", "Замена пермопасты на чипе видеокарты" },
                            PageId = 3,
                            Service = "Чистка ноутбука от пыли с заменой термопасты",
                            ServiceName = "Обслуживание ноутбука",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 38,
                            IdServiceName = "router-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка и базовая настройка роутера", "Индивидуальная настройка роутера (настройка \"проброса\" портов, удаленного доступа, выбор оптимального канала вещания WiFi)", "Сброс настроек, повторная настройка роутера", "Замена прошивки роутера", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Установка роутера",
                            ServiceName = "Настройка роутера",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 39,
                            IdServiceName = "router-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка и базовая настройка Wi-Fi роутера", "Индивидуальная настройка Wi-Fi роутера (настройка \"проброса\" портов, удаленного доступа, выбор оптимального канала вещания WiFi)", "Работы по улучшению сигнала Wi-Fi сети", "Настройка безопасности Wi-Fi сети", "Сброс настроек, повторная настройка Wi-Fi роутера", "Замена прошивки Wi-Fi роутера", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Настройка Wi-Fi сети",
                            ServiceName = "Настройка роутера",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 40,
                            IdServiceName = "router-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Работы по улучшению сигнала Wi-Fi сети", "Сброс настроек, повторная настройка роутера", "Замена прошивки роутера", "Ремонт роутера", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Устранение неполадок роутера",
                            ServiceName = "Настройка роутера",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 41,
                            IdServiceName = "internet-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка и базовая настройка роутера", "Настройка сетевой платы", "Настройка сети Интернет по Wi-Fi сети", "Обжим кабеля коннектором RJ-45", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Настройка доступа к сети Интернет",
                            ServiceName = "Интернет",
                            ServicePrice = "1000"
                        },
                        new
                        {
                            PriceListId = 42,
                            IdServiceName = "internet-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка сетевого оборудования", "Прокладка сетевого кабеля", "Обжим кабеля коннектором RJ-45", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Прокладка сетевого кабеля",
                            ServiceName = "Интернет",
                            ServicePrice = "За метр 500"
                        },
                        new
                        {
                            PriceListId = 43,
                            IdServiceName = "internet-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Антивирусная профилактика", "Настройка сетевой платы для обеспечения доступа к сети Интернет", "Поиск и устранение неисправностей сетевого оборудования", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Устранение неполадок сети Инернет",
                            ServiceName = "Интернет",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 44,
                            IdServiceName = "lan-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Настройка работы роутера в локальной сети", "Настройка сетевой платы", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Настройка локальной сети",
                            ServiceName = "Локальная сеть",
                            ServicePrice = "1000"
                        },
                        new
                        {
                            PriceListId = 45,
                            IdServiceName = "lan-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Антивирусная профилактика", "Настройка сетевой платы", "Настройка сетевого оборудования", "Поиск и устранение неисправностей сетевого оборудования", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Устранение неполадок локальной сети",
                            ServiceName = "Локальная сеть",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 46,
                            IdServiceName = "lan-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Установка сетевого оборудования", "Прокладка сетевого кабеля", "Обжим кабеля коннектором RJ-45", "Прочие необходимые работы" },
                            PageId = 5,
                            Service = "Прокладка сетевого кабеля",
                            ServiceName = "Локальная сеть",
                            ServicePrice = "За метр 500"
                        },
                        new
                        {
                            PriceListId = 47,
                            IdServiceName = "data-recovery",
                            NeedWorks = new[] { "Восстановление данных (случайно удаленные фотографии, документы. Случаи, когда повреждена таблица файловой системы)" },
                            PageId = 6,
                            Service = "Восстановление данных с жесткого диска",
                            ServiceName = "Восстановление данных",
                            ServicePrice = "6000"
                        },
                        new
                        {
                            PriceListId = 48,
                            IdServiceName = "data-recovery",
                            NeedWorks = new[] { "Восстановление данных (случайно удаленные фотографии, документы; cлучаи, когда повреждена таблица файловой системы)" },
                            PageId = 6,
                            Service = "Восстановление информации с флеш-накопителя",
                            ServiceName = "Восстановление данных",
                            ServicePrice = "6000"
                        },
                        new
                        {
                            PriceListId = 49,
                            IdServiceName = "data-recovery",
                            NeedWorks = new[] { "Восстановление данных (случайно удаленные фотографии, документы; cлучаи, когда повреждена таблица файловой системы)" },
                            PageId = 6,
                            Service = "Восстановление данных с SD-карты",
                            ServiceName = "Восстановление данных",
                            ServicePrice = "6000"
                        },
                        new
                        {
                            PriceListId = 50,
                            IdServiceName = "data-recovery",
                            NeedWorks = new[] { "Восстановление данных (случайно удаленные фотографии, документы; cлучаи, когда повреждена таблица файловой системы)" },
                            PageId = 6,
                            Service = "Восстановление данных с SSD-диска",
                            ServiceName = "Восстановление данных",
                            ServicePrice = "6000"
                        },
                        new
                        {
                            PriceListId = 51,
                            IdServiceName = "b2b",
                            NeedWorks = new[] { "1 (один) плановый выезд специалиста в месяц", "Полная техническая профилактика всего парка компьютеров", "Полная антивирусная профилактика всего парка компьютеров", "Устранение текущих неполадок (возможно, силами стороннего подрядчика)", "Консультации сотрудников по работе с компьютерами" },
                            PageId = 7,
                            Service = "Абонентское обслуживание компьютеров",
                            ServiceName = "ИТ-услуги для бизнеса",
                            ServicePrice = "1000 рублей в месяц за один компьютер"
                        },
                        new
                        {
                            PriceListId = 52,
                            IdServiceName = "b2b",
                            NeedWorks = new[] { "1 (один) плановый выезд специалиста в месяц", "Полная техническая профилактика всего парка оргтехники", "Устранение текущих неполадок (возможно, силами стороннего подрядчика)", "Консультации сотрудников по работе с оргтехникой" },
                            PageId = 7,
                            Service = "Абонентское обслуживание оргтехники",
                            ServiceName = "ИТ-услуги для бизнеса",
                            ServicePrice = "1000 рублей в месяц за единицу оборудования"
                        },
                        new
                        {
                            PriceListId = 53,
                            IdServiceName = "b2b",
                            NeedWorks = new[] { "Необходимые работы определяются заказчиком" },
                            PageId = 7,
                            Service = "Внеплановый выезд специалиста",
                            ServiceName = "ИТ-услуги для бизнеса",
                            ServicePrice = "1000 рублей за внеплановый выезд"
                        },
                        new
                        {
                            PriceListId = 54,
                            IdServiceName = "printer-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Поиск и установка драйвера устройства", "Подключение и базовая настройка принтера", "Настройка работы принтера по Wi-Fi сети", "Индивидуальная настройка принтера", "Прочие необходимые работы" },
                            PageId = 10,
                            Service = "Настройка принтера",
                            ServiceName = "Принтеры",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 55,
                            IdServiceName = "printer-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Чистка и профилактика принтера", "Полная чистка и смазка с частичной разборкой принтера", "Прочие необходимые работы" },
                            PageId = 10,
                            Service = "Очистка принтера",
                            ServiceName = "Принтеры",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 56,
                            IdServiceName = "printer-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Восстановление работоспособности печатающей головки струйного принтера", "Ремонт электроники принтера", "Замена фотоцилиндра, магнитного вала или ракеля лазерного принтера", "Прочие необходимые работы" },
                            PageId = 10,
                            Service = "Ремонт принтера",
                            ServiceName = "Принтеры",
                            ServicePrice = "5000"
                        },
                        new
                        {
                            PriceListId = 57,
                            IdServiceName = "mfd-config",
                            NeedWorks = new[] { "Поиск и установка драйвера устройства", "Подключение и базовая настройка МФУ", "Калибровка сканирующей части МФУ", "Настройка работы МФУ по Wi-Fi сети", "Настройка работы МФУ по локальной сети", "Индивидуальная настройка МФУ", "Прочие необходимые работы" },
                            PageId = 10,
                            Service = "Настройка МФУ",
                            ServiceName = "Многофункциональное устройство (МФУ)",
                            ServicePrice = "2000"
                        },
                        new
                        {
                            PriceListId = 58,
                            IdServiceName = "mfd-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Чистка и профилактика МФУ", "Полная чистка и смазка с частичной разборкой МФУ", "Калибровка сканирующей части МФУ", "Прочие необходимые работы" },
                            PageId = 10,
                            Service = "Очистка МФУ",
                            ServiceName = "Многофункциональное устройство (МФУ)",
                            ServicePrice = "2500"
                        },
                        new
                        {
                            PriceListId = 59,
                            IdServiceName = "mfd-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Восстановление работоспособности печатающей головки струйного МФУ", "Ремонт электроники МФУ", "Замена фотоцилиндра, магнитного вала или ракеля лазерного МФУ", "Ремонт сканирующей части МФУ", "Прочие необходимые работы" },
                            PageId = 10,
                            Service = "Ремонт МФУ",
                            ServiceName = "Многофункциональное устройство (МФУ)",
                            ServicePrice = "5500"
                        },
                        new
                        {
                            PriceListId = 60,
                            IdServiceName = "scanner-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Поиск и установка драйвера устройства", "Подключение и базовая настройка сканера", "Калибровка сканера", "Настройка работы сканера по Wi-Fi сети", "Настройка работы сканера по локальной сети", "Индивидуальная настройка сканера", "Прочие необходимые работы" },
                            PageId = 10,
                            Service = "Настройка сканера",
                            ServiceName = "Сканирующие устройства (сканеры)",
                            ServicePrice = "1500"
                        },
                        new
                        {
                            PriceListId = 61,
                            IdServiceName = "scanner-config",
                            NeedWorks = new[] { "Диагностика оборудования", "Ремонт инвертора лампы подсветки", "Замена лампы подсветки", "Ремонт других электронных узлов сканера", "Ремонт механики сканирующей головки", "Прочие необходимые работы" },
                            PageId = 10,
                            Service = "Ремонт сканера",
                            ServiceName = "Сканирующие устройства (сканеры)",
                            ServicePrice = "5000"
                        });
                });

            modelBuilder.Entity("CompanyProject.Domain.EmployeeAggregate.EmployeeCustomer", b =>
                {
                    b.HasOne("CompanyProject.Domain.CustomerAggregate.Customer", "Customer")
                        .WithMany("EmployeeCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyProject.Domain.EmployeeAggregate.Employee", "Employee")
                        .WithMany("EmployeeCustomers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyProject.Domain.FeedbackAggregate.Feedback", b =>
                {
                    b.HasOne("CompanyProject.Domain.OrderAggregate.Order", "Order")
                        .WithOne("Feedback")
                        .HasForeignKey("CompanyProject.Domain.FeedbackAggregate.Feedback", "OrderForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyProject.Domain.OrderAggregate.Order", b =>
                {
                    b.HasOne("CompanyProject.Domain.CustomerAggregate.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyProject.Domain.EmployeeAggregate.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyProject.Domain.ParagraphAggregate.Paragraph", b =>
                {
                    b.HasOne("CompanyProject.Domain.PageAggregate.Page", "Page")
                        .WithMany("Paragraphs")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyProject.Domain.PriceListAggregate.PriceList", b =>
                {
                    b.HasOne("CompanyProject.Domain.PageAggregate.Page", "Page")
                        .WithMany("PriceLists")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
