// <auto-generated />
using System;
using CompanyProjectCardsService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyProjectCardsService.Migrations
{
    [DbContext(typeof(CompanyProjectCardDbContext))]
    partial class CompanyProjectCardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyProjectCardsService.Model.CardFooterItem", b =>
                {
                    b.Property<Guid>("CardFooterItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardFooterItemContent")
                        .HasColumnType("text");

                    b.Property<bool>("CardFooterItemIsLink")
                        .HasColumnType("boolean");

                    b.Property<string>("CardFooterItemLinkAction")
                        .HasColumnType("text");

                    b.Property<string>("CardFooterItemLinkController")
                        .HasColumnType("text");

                    b.Property<Guid?>("MainCardId")
                        .HasColumnType("uuid");

                    b.HasKey("CardFooterItemId");

                    b.HasIndex("MainCardId");

                    b.ToTable("CardFooterItem");

                    b.HasData(
                        new
                        {
                            CardFooterItemId = new Guid("aa78bffb-0326-4d35-b238-99404a20c4a8"),
                            CardFooterItemIsLink = false
                        });
                });

            modelBuilder.Entity("CompanyProjectCardsService.Model.MainCard", b =>
                {
                    b.Property<Guid>("MainCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("CardContent")
                        .HasColumnType("text[]");

                    b.Property<bool>("CardHasFooter")
                        .HasColumnType("boolean");

                    b.Property<bool>("CardHasHeader")
                        .HasColumnType("boolean");

                    b.Property<bool>("CardHasImage")
                        .HasColumnType("boolean");

                    b.Property<string[]>("CardHeaderContent")
                        .HasColumnType("text[]");

                    b.Property<string>("CardHeaderIcon")
                        .HasColumnType("text");

                    b.Property<bool>("CardHeaderIsLink")
                        .HasColumnType("boolean");

                    b.Property<string>("CardHeaderLinkAction")
                        .HasColumnType("text");

                    b.Property<string>("CardHeaderLinkController")
                        .HasColumnType("text");

                    b.Property<string>("CardImage")
                        .HasColumnType("text");

                    b.Property<bool>("CardIsLink")
                        .HasColumnType("boolean");

                    b.Property<string>("CardLinkAction")
                        .HasColumnType("text");

                    b.Property<string>("CardLinkController")
                        .HasColumnType("text");

                    b.Property<string>("PageNameForCard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MainCardId");

                    b.HasIndex("PageNameForCard");

                    b.ToTable("MainCards");

                    b.HasData(
                        new
                        {
                            MainCardId = new Guid("d527d592-ba09-4265-8eba-1a87346d200d"),
                            CardContent = new[] { "Image_ComputersRepair.png" },
                            CardHasFooter = false,
                            CardHasHeader = true,
                            CardHasImage = false,
                            CardHeaderContent = new[] { "Ремонт компьютеров" },
                            CardHeaderIsLink = false,
                            CardIsLink = true,
                            CardLinkAction = "ComputersRepair",
                            CardLinkController = "Home",
                            PageNameForCard = "Index"
                        },
                        new
                        {
                            MainCardId = new Guid("1d4a6dab-3743-459d-97e2-5018a01b5e11"),
                            CardContent = new[] { "Image_LaptopsRepair.png" },
                            CardHasFooter = false,
                            CardHasHeader = true,
                            CardHasImage = false,
                            CardHeaderContent = new[] { "Ремонт ноутбуков" },
                            CardHeaderIsLink = false,
                            CardIsLink = true,
                            CardLinkAction = "LaptopsRepair",
                            CardLinkController = "Home",
                            PageNameForCard = "Index"
                        },
                        new
                        {
                            MainCardId = new Guid("d81ce3ba-b404-43c5-a848-963ef8fdcd3f"),
                            CardContent = new[] { "Image_HelpDesk.png" },
                            CardHasFooter = false,
                            CardHasHeader = true,
                            CardHasImage = false,
                            CardHeaderContent = new[] { "Компьютерная помощь" },
                            CardHeaderIsLink = false,
                            CardIsLink = true,
                            CardLinkAction = "HelpDesk",
                            CardLinkController = "Home",
                            PageNameForCard = "Index"
                        },
                        new
                        {
                            MainCardId = new Guid("e8aa9a89-0472-4668-b182-9a3af235512a"),
                            CardContent = new[] { "Image_InternetNetworks.png" },
                            CardHasFooter = false,
                            CardHasHeader = true,
                            CardHasImage = false,
                            CardHeaderContent = new[] { "Интернет и сети" },
                            CardHeaderIsLink = false,
                            CardIsLink = true,
                            CardLinkAction = "InternetNetworks",
                            CardLinkController = "Home",
                            PageNameForCard = "Index"
                        },
                        new
                        {
                            MainCardId = new Guid("8baa4bdb-3534-4a09-b647-5baaeb935bc2"),
                            CardContent = new[] { "Image_DataRecovery.png" },
                            CardHasFooter = false,
                            CardHasHeader = true,
                            CardHasImage = false,
                            CardHeaderContent = new[] { "Восстановление данных" },
                            CardHeaderIsLink = false,
                            CardIsLink = true,
                            CardLinkAction = "DataRecovery",
                            CardLinkController = "Home",
                            PageNameForCard = "Index"
                        },
                        new
                        {
                            MainCardId = new Guid("a7b1e1e2-d028-4858-bff5-4e77dcaf2141"),
                            CardContent = new[] { "Image_B2b.png" },
                            CardHasFooter = false,
                            CardHasHeader = true,
                            CardHasImage = false,
                            CardHeaderContent = new[] { "ИТ-услуги для бизнеса" },
                            CardHeaderIsLink = false,
                            CardIsLink = true,
                            CardLinkAction = "B2b",
                            CardLinkController = "Home",
                            PageNameForCard = "Index"
                        },
                        new
                        {
                            MainCardId = new Guid("31022cbe-59ba-46a4-a492-d143369416ed"),
                            CardContent = new[] { "Image_LaptopUpgrade.png" },
                            CardHasFooter = false,
                            CardHasHeader = true,
                            CardHasImage = false,
                            CardHeaderContent = new[] { "Модернизация ноутбука" },
                            CardHeaderIsLink = false,
                            CardIsLink = true,
                            CardLinkAction = "LaptopUpgrade",
                            CardLinkController = "Home",
                            PageNameForCard = "Index"
                        },
                        new
                        {
                            MainCardId = new Guid("47b3ce27-e5c0-4563-9219-5433684bcfb4"),
                            CardContent = new[] { "Image_PcAssembly.png" },
                            CardHasFooter = false,
                            CardHasHeader = true,
                            CardHasImage = false,
                            CardHeaderContent = new[] { "Сборка компьютера" },
                            CardHeaderIsLink = false,
                            CardIsLink = true,
                            CardLinkAction = "PcAssembly",
                            CardLinkController = "Home",
                            PageNameForCard = "Index"
                        });
                });

            modelBuilder.Entity("CompanyProjectCardsService.Model.CardFooterItem", b =>
                {
                    b.HasOne("CompanyProjectCardsService.Model.MainCard", null)
                        .WithMany("CardFooterItems")
                        .HasForeignKey("MainCardId");
                });

            modelBuilder.Entity("CompanyProjectCardsService.Model.MainCard", b =>
                {
                    b.Navigation("CardFooterItems");
                });
#pragma warning restore 612, 618
        }
    }
}
