// <auto-generated />
using System;
using CompanyProjectContent.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyProjectContent.Migrations
{
    [DbContext(typeof(CompanyProjectContentDbContext))]
    [Migration("20220627212209_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyProjectContent.Models.Page.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PageId"));

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScreenName")
                        .HasColumnType("text");

                    b.Property<bool>("ToCard")
                        .HasColumnType("boolean");

                    b.Property<bool>("ToNavbar")
                        .HasColumnType("boolean");

                    b.HasKey("PageId");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            PageId = 1,
                            Name = "Index",
                            ToCard = false,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 2,
                            Icon = "fas fa-wrench",
                            Name = "ComputersRepair",
                            ScreenName = "Ремонт компьютеров",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 3,
                            Icon = "fas fa-laptop-medical",
                            Name = "LaptopsRepair",
                            ScreenName = "Ремонт ноутбуков",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 4,
                            Icon = "fas fa-ambulance",
                            Name = "HelpDesk",
                            ScreenName = "Компьютерная помощь",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 5,
                            Icon = "fas fa-network-wired",
                            Name = "InternetNetworks",
                            ScreenName = "Интернет и сети",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 6,
                            Icon = "fas fa-database",
                            Name = "DataRecovery",
                            ScreenName = "Восстановление данных",
                            ToCard = true,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 7,
                            Icon = "fas fa-industry",
                            Name = "B2b",
                            ScreenName = "ИТ-услуги для бизнеса",
                            ToCard = true,
                            ToNavbar = true
                        },
                        new
                        {
                            PageId = 8,
                            Icon = "fas fa-laptop",
                            Name = "LaptopUpgrade",
                            ScreenName = "Модернизация ноутбука",
                            ToCard = true,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 9,
                            Icon = "fas fa-tv",
                            Name = "PcAssembly",
                            ScreenName = "Сборка компьютера",
                            ToCard = true,
                            ToNavbar = false
                        },
                        new
                        {
                            PageId = 10,
                            Icon = "fas fa-print",
                            Name = "OfficeEquipment",
                            ScreenName = "Oргтехника",
                            ToCard = false,
                            ToNavbar = true
                        });
                });

            modelBuilder.Entity("CompanyProjectContent.Models.Paragraph.Paragraph", b =>
                {
                    b.Property<int>("ParagraphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParagraphId"));

                    b.Property<string[]>("Content")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("HasPicture")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlobalTitle")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsList")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMobileVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubtitle")
                        .HasColumnType("boolean");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("PicturePath")
                        .HasColumnType("text");

                    b.HasKey("ParagraphId");

                    b.HasIndex("PageId");

                    b.ToTable("Paragraphs");

                    b.HasData(
                        new
                        {
                            ParagraphId = 1,
                            Content = new[] { "Ремонт и обслуживание компьютерной техники на Кавказских Минеральных Водах" },
                            HasPicture = false,
                            IsGlobalTitle = true,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 2,
                            Content = new[] { "Компания «Нова Компьютерс» предлагает Вам качественные и недорогие компьютерные услуги по обслуживанию, ремонту компьютеров, ноутбуков и офисной техники в регионе Кавказских Минеральных Вод (Минеральные Воды, Пятигорск, Ессентуки, Кисловодск). Ремонт может проводиться как территории заказчика, так и в нашем сервисном центре. Мы всегда рады оперативно оказать Вам профессиональную компьютерную помощь, обращайтесь!" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 3,
                            Content = new[] { "_NeedHelpAndPicturePartial" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = false,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 4,
                            Content = new[] { "Вызов компьютерного мастера на дом" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 5,
                            Content = new[] { "Высококвалифицированные специалисты компании «Нова Компьютерс» имеют большой опыт в ремонте и обслуживании любых моделей компьютеров, ноутбуков, роутеров и других видов цифровой и вычислительной техники.", "Для определения неполадок компьютера или ноутбука нашему специалисту необходимо провести начальную диагностику Вашего оборудования, с целью составления сметы на ремонт.", "Наши мастера делают только те работы, которые необходимы; <b>мы никогда не занимаемся навязыванием дополнительных, зачастую ненужных, услуг.</b>" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 6,
                            Content = new[] { "Как вызвать компьютерного мастера на дом или в офис?" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 7,
                            Content = new[] { "Позвоните нам или оставьте заявку на сайте в соответствующей форме;", "Опишите Вашу проблему;", "Согласуйте время приезда компьютерного мастера." },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = true,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 8,
                            Content = new[] { "Оказываем услуги по ремонту в городах Кавказских Минеральных Вод (Минеральные Воды, Пятигорск, Ессентуки, Кисловодск) и в прилегающих населенных пунктах." },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 9,
                            Content = new[] { "Как скоро приедет мастер? Сколько будут стоить услуги по ремонту?" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 10,
                            Content = new[] { "Мастер приедет в заранее согласованное с Вами время;", "Перед началом работ по настройке или ремонту компьютера, ноутбука или офисной техники специалисту необходимо будет провести диагностику;", "Подробные цены на ремонт и компьютерные услуги компании «Нова Компьютерс» Вы можете узнать в разделе \"Цены\"." },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = true,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 11,
                            Content = new[] { "Ремонт компьютеров на дому или в офисе" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 12,
                            Content = new[] { "Мы готовы помочь Вам с ремонтом компьютерной техники. Специалисты нашей компании выполняют профессиональный ремонт компьютеров любых производителей недорого и в минимально возможные сроки." },
                            HasPicture = true,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1,
                            PicturePath = "~/Resources/Images/remont-komputerov.jpg"
                        },
                        new
                        {
                            ParagraphId = 13,
                            Content = new[] { "Каков порядок ремонта компьютерной техники? Где будут выполняться работы?" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 14,
                            Content = new[] { "Ремонт стационарных компьютеров может выполняться как у Вас на дому или в офисе, так и у нас в сервисном центре;", "Может потребоваться специальное оборудование или дополнительные запчасти. В этом случае наш специалист при Вашем желании может доставить компьютер в сервисный центр, провести работы по ремонту, а затем привезти обратно к Вам." },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = true,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 15,
                            Content = new[] { "Компьютерная помощь срочно и без проблем!" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 16,
                            Content = new[] { "Компания «Нова Компьютерс» всегда рада оказать Вам срочную компьютерную помощь! Мы выполним любые Ваши пожелания по ремонту и настройке компьютера, ноутбука, роутера, МФУ, принтера. Так же поможем установить Windows или иную операционную систему, скачать и установить любые программы и утилиты." },
                            HasPicture = true,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1,
                            PicturePath = "~/Resources/Images/komputernaya-pomosh.png"
                        },
                        new
                        {
                            ParagraphId = 17,
                            Content = new[] { "Какие услуги компьютерной помощи мы можем оказать?" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = false,
                            IsMobileVisible = true,
                            IsSubtitle = true,
                            PageId = 1
                        },
                        new
                        {
                            ParagraphId = 18,
                            Content = new[] { "В число компьютерных услуг входит так же помощь по установке антивирусов, драйверов, обучение пользователей работе на компьютере и прочее;", "Учтем все Ваши пожелания, обращайтесь! Мы поможем!" },
                            HasPicture = false,
                            IsGlobalTitle = false,
                            IsList = true,
                            IsMobileVisible = true,
                            IsSubtitle = false,
                            PageId = 1
                        });
                });

            modelBuilder.Entity("CompanyProjectContent.Models.Paragraph.Paragraph", b =>
                {
                    b.HasOne("CompanyProjectContent.Models.Page.Page", "Page")
                        .WithMany("Paragraphs")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("CompanyProjectContent.Models.Page.Page", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
